package com.vaibhav.samples.prep;

public class FibonacciRecursive {

    //The fibonacci number is generated by adding the previous two numbers – F(N) = F(N-1) + F(N-2). We can use recursion to print fibonacci series.
    public static void main(String[] args){
        System.out.println(fibRecursive(10));
    }

    public static int fibRecursive(int n){
        if(n <= 1) return n;
        return fibRecursive(n-1)+ fibRecursive(n-2);
    }
}
